name: Flutter Build AppBundle

on:
  push:
    branches:
      - master
  workflow_dispatch:
  
jobs:
  build:
    runs-on: ubuntu-latest

    steps:
    - name: Checkout repository
      uses: actions/checkout@v3

    - name: Set up Flutter
      uses: subosito/flutter-action@v2
      with:
        flutter-version: stable

    - name: Install dependencies
      run: flutter pub get

    - name: Build appbundle
      run: flutter build appbundle

    - name: Upload appbundle
      uses: actions/upload-artifact@v4
      with:
        name: appbundle
        path: build/app/outputs/bundle/release/app-release.aab
